Fix: compiler error "'DefaultPersistenceResultHandler' incorrectly implements interface 'PersistenceResultHandler'" when strictFunctionTypes flag is on
With strictFunctionTypes flag on in an Angular 5 project with Typescript@2.6.2, the project is failed to compile with the following error message: 

```
ERROR in node_modules/ngrx-data/dataservices/persistence-result-handler.service.d.ts(18,22): error TS2420: Class 'DefaultPersistenceResultHandler' incorrectly implements interface 'PersistenceResultHandler'.
  Types of property 'handleError' are incompatible.
    Type '(action: EntityAction<any>) => (error: DataServiceError) => Observable<EntityAction<EntityActionD...' is not assignable to type '(action: EntityAction<any>) => (error: Error | DataServiceError) => Observable<Action>'.
      Type '(error: DataServiceError) => Observable<EntityAction<EntityActionDataServiceError>>' is not assignable to type '(error: Error | DataServiceError) => Observable<Action>'.
        Types of parameters 'error' and 'error' are incompatible.
          Type 'Error | DataServiceError' is not assignable to type 'DataServiceError'.
            Type 'Error' is not assignable to type 'DataServiceError'.
              Property 'error' is missing in type 'Error'.
```
The PR would make the typings consistent and remove the error.